export const HistoryType = {
    GROUP: "GROUP",
    DEPARTMENT: "DEPARTMENT",
    STUDENT: "STUDENT",
    TEACHER: "TEACHER",
    SUBJECT: "SUBJECT",
    SPECIALITY: "SPECIALITY",
    DIRECTOR: "DIRECTOR",
    DEPARTMENT_HEAD: "DEPARTMENT_HEAD "
}